version: '3.8'

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:1.0
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    expose:
      - "3350"
    networks:
      - inception
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$$(cat /run/secrets/db_root_password)"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:1.0
    volumes:
      - wordpress_data:/var/www/html
    secrets:
      - db_password
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    expose:
      - "9000"
    networks:
      - inception
    restart: unless-stopped

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:1.0
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

    
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mhamidi/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mhamidi/data/wordpress
      

networks:
  inception:
    driver: bridge